### ISSUE TITLE
Game crash after retrying Insomnia

### ISSUE THREAD

**Issue by TheLemon27** [Starmapo/Lullaby-Forever-Fix#3]
I was playing Insomnia in the Lost Silver week and when I retried the song, the game crashed with the following error message:
`vlc/bitmap/VlcBitmap.hx (line 526)`
`vlc/MP4Handler.hx (line 88)`
`meta/subState/GameOverSubstate.hx (line 639)`
`meta/subState/GameOverSubstate.hx (line 823)`
`meta/subState/GameOverSubstate.hx (line 782)`
`flixel/FlxState.hx (line 203)`
`flixel/FlxState.hx (line 212)`
`flixel/FlxGame.hx (line 752)`
`flixel/FlxGame.hx (line 682)`
`flixel/FlxGame.hx (line 556)`
`openfl/events/EventDispatcher.hx (line 402)`
`openfl/display/DisplayObject.hx (line 1399)`

`Uncaught Error: Null Object Reference`
Just like with the Frostbite crash, it was working perfectly fine yesterday.

**Comment by Starmapo** [comment]
This should now be fixed in the next update. Thanks for reporting the issue👍

**Comment by TheLemon27** [comment]
ok, and it seems to have fixed itself for me too somehow

**Comment by Starmapo** [comment]
It only happened to me when I pressed enter while the video animation hadn't finished. Does it still happen if you do that?

**Comment by TheLemon27** [comment]
well, i know it didn't happen just because of that for me, because one time i was showing it to someone else, and i left it on the "retry?" screen for a bit, and it still crashed when I tried to retry.
oh and i tested it, It didn't crash when I did it now.

**Comment by Starmapo** [comment]
Huh, that's strange. I haven't gotten any crashes on my current build, so it should hopefully still be fixed.
